spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shopping-mall
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
#      ddl-auto: create    # 애플리케이션 실행 시점에 테이블을 drop하고, 다시 생성한다.
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    org.hibernate.SQL: debug    # logger를 통해 hibernate 실행 SQL을 남긴다.
    org.hibernate.type: trace