spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/exercise
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create      # 애플리케이션 실행 시점에 자동으로 테이블 삭제, 생성
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace